extends Node

enum LANGUAGE {ITA, ENG}

enum FACTION {NEUTRAL, GOOD, BAD}
enum TYPE {NOTYPE, BUTTERFLY, MOSQUITO}
enum ACHIEVEMENT {
	NO_ACHIEVEMENT,
	HIT_BABY,
	COMPLETED_MOSQUITOES,
	JOFFREY,
	JOFFREY_2,
	PIDGEON,
	LADY_BUTT,
	FIRST_BUTTERFLY,
	COMPLETED_BUTTERFLIES,
	NO_TUTORIAL,
	HORSE,
	SHEEP,
	AVOID_DEATH,
	AVOID_DEATH_2,
	CACTUS,
}
